/**
 * GraphQL codegen for @agent-town/graphclient.
 * Schema: local packages/subgraph/schema.graphql (no live introspection).
 * Outputs typed operations + graphql-request SDK under src/generated/.
 */
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: ["../subgraph/schema.graphql", "src/schema-codegen.graphql"],
  documents: ["src/**/*.graphql"],
  generates: {
    "src/generated/graphql.ts": {
      plugins: [
        {
          add: {
            content: [
              "// @ts-nocheck — generated by graphql-codegen",
              "class TypedDocumentString extends String {",
              "  constructor(value, meta) { super(value); this.value = value; this.__meta__ = meta; }",
              "  toString() { return this.value; }",
              "}",
            ].join("\n"),
          },
        },
        "typescript",
        "typescript-operations",
        "typescript-graphql-request",
      ],
      config: {
        scalars: {
          BigInt: "string",
          Bytes: "string",
          Timestamp: "string",
          Int8: "string",
        },
        avoidOptionals: {
          field: true,
          inputValue: false,
          object: false,
          defaultValue: false,
        },
        enumsAsTypes: true,
        skipTypename: true,
        rawRequest: false,
        documentMode: "string",
      },
    },
  },
};

export default config;
